# Site settings
title: KEVIN OLEGA SERVICES
email: kevin@olega.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: kevinolega
github_username: 
sendfox_username: kevinolega

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

gems: [jekyll-seo-tag, jekyll-redirect-from ]
