title: KEVIN OLEGA SERVICES
author: Kevin Olega
email: kevinolegaservices@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Turn your ideas into reality

twitter_username: kevinolega
github_username:  kevinolega

sass:
    style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

gems: [jekyll-seo-tag, jekyll-paginate, jekyll-feed, jekyll-redirect-from ]
